### ISSUE TITLE
FPS of TraDeS on VIS task

### ISSUE THREAD

**Issue by zhangxgu** [JialianW/TraDeS#1]
Hi, thanks for your excellent work!
I want to know the FPS of TraDeS on YouTube-VIS. Have you ever evaluate the speed on this dataset?

**Comment by JialianW** [comment]
Thanks for your interest! The speed of TraDeS on Youtube-VIS is 38ms per image. We did not put it on the table due to limited space. The proposed modules in TraDeS are very efficient and do not introduce much speed overhead.

**Comment by zhangxgu** [comment]
Thanks!!!!!

**Comment by zhangxgu** [comment]
By the way, is this 38ms the tot_time of all inference steps including post_time and load_time?

**Comment by JialianW** [comment]
No, it does not include pre- and post-processing time.
