### ISSUE TITLE
DCN_TraDeS

### ISSUE THREAD

**Issue by xuranran123456** [JialianW/TraDeS#14]
ImportError: cannot import name 'DCN_TraDeS' from 'model.networks.DCNv2.dcn_v2' (/raid/xr/TraDeS-master/src/lib/model/networks/DCNv2/dcn_v2.py)

**Comment by Hayoung93** [comment]
@xuranran123456  Did you check the file dcn_v2.py? You should use the modified version, provided by TraDeS' author.

But I failed to run the demo code even though I followed INSTALL.md :(

**Comment by JialianW** [comment]
You should use the provided DCN folder not from other repo, as the dcn_v2.py was modified by us accordingly.

**Comment by JialianW** [comment]
> @xuranran123456 Did you check the file dcn_v2.py? You should use the modified version, provided by TraDeS' author.
> 
> But I failed to run the demo code even though I followed INSTALL.md :(

Feel free to propose specific issue. We can successfully perform the demo on our end according to the INSTALL.md.
