### ISSUE TITLE
demo parameters

### ISSUE THREAD

**Issue by pqviet** [JialianW/TraDeS#25]
I have tried the demo (with default parameters) on a very simple video which is tracking only 1 person, and found 2 following problems
1) If it fails to detect the person at the current frame, it will assign a new track ID at the next frame
2) Sometimes there are 2 overlapped detection boxes (with different track IDs) with very high IOU at the same place
How can I fine-tune the default parameters to  overcome these problems?

**Comment by JialianW** [comment]
1. We recommend you use the Crowdhuman pretrained model to test your own video.

2. Yes, in some cases, it will assign a new ID if it has low matching score with previous targets.

3. You can use box NMS to filter out highly overlapped boxes.

**Comment by pqviet** [comment]
Where can I change the track matching score and box NMX? Thanks.

**Comment by JialianW** [comment]
You can change the matching score threshold here: https://github.com/JialianW/TraDeS/blob/3eafd249ca0f18af8000d5798d4c552a0bd627ec/src/lib/utils/tracker.py#L136

For using box NMS, try to add like this --box_nms 0.7 for your commend.

**Comment by Moaz-Morsy** [comment]
how can we test segmentaion model? @JialianW

**Comment by JialianW** [comment]
> how can we test segmentaion model? @JialianW

See https://github.com/JialianW/TraDeS/issues/24#issue-926460590
