### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by Leo63963** [JialianW/TraDeS#27]
Hi 
Thanks for the work, really adimre that

There is a question about the code, in the follow:
https://github.com/JialianW/TraDeS/blob/3eafd249ca0f18af8000d5798d4c552a0bd627ec/src/lib/utils/tracker.py#L196

Why you invalid the last embedding while measuring the similarity?
I tried run the code without this, and the IDF1 drops (0.1), which means it is important.

Many thanks.

**Comment by JialianW** [comment]
Because the last one is the object itself. It needs to ignore the cosine sim for itself.

**Comment by Leo63963** [comment]
Thanks for the reply.

Just one follow-up.
the cosine sim here: cos(a, b)
https://github.com/JialianW/TraDeS/blob/3eafd249ca0f18af8000d5798d4c552a0bd627ec/src/lib/utils/tracker.py#L193
The a is unmatched detections, the b should be unmatched and histoy tracks, thus I personally think that the last one may not the object itself. Besides, by debug, I found the _cos[nID-1]_  is not close to 1 (should be 1 for the same object).

Thanks

**Comment by JialianW** [comment]
Sorry, I haven't been back to this code for a long time. I just remembered that I mask out the object itself. If the nID-1 is not the object itself, then that line should be removed and it should be a bug. We only need to mask out the alive tracking id and different classes tracking id. If it only drops 0.1 IDF1, it should be fine. Thanks for the reminder!

**Comment by Leo63963** [comment]
Thanks for the reply. 
Really admire your work.
