### ISSUE TITLE
CUDA error when training youtube-vis

### ISSUE THREAD

**Issue by andrewfengusa** [JialianW/TraDeS#32]
Hi,

I tried to follow the instruction in [https://github.com/JialianW/TraDeS/blob/3eafd249ca0f18af8000d5798d4c552a0bd627ec/experiments/youtube_vis.sh](url) to train the segmentation model. 

However, I encountered a Runtime CUDA error during training 
```
File "/anaconda3/envs/trades/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/anaconda3/envs/trades/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
python-BaseException
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1573049301898/work/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=77 : an illegal memory access was encountered
```

Originally I thought it is due to out of memory. However, reducing the batch size doesn't seem to fix this error. Any tips for the possible cause and fix for this? Thanks!

**Comment by JialianW** [comment]
"an illegal memory access was encountered" usually happens when index is out of range. You can check the number classes and labels.
