### ISSUE TITLE
How to try to train a model of our own（crowdhuman dataset）

### ISSUE THREAD

**Issue by 15835111234** [JialianW/TraDeS#35]
We use the script and data set you provide to try training ；Training is ok, but an error is reported during verificationwe  ：assert len(cost_volume_track_ids) == self.opt.clip_len 。

Use our own data set to also include such errors 。

**Comment by JialianW** [comment]
Thanks for the interests!

Did you try the testing script? What do you mean by verification? We didn't provide code for evaluating the model while training.
