### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by mustansarfiaz** [JialianW/TraDeS#38]
Respected @JialianW

I found your paper very interesting. You did a great job.

I wanted to test the MOT17 dataset and evaluate the model using your trained model.
I changed the test.py file according to mot17_test.sh

I set parameters as:
 'pre_hm' to default=True' (Should I set to False?)

In detector.py file,
I get error that "self.pre_hms" is not found.
Therefore, I added self.pre_hms = opt.pre_hm
And at line 362,  output, current_feat = self.model(images, pre_images, pre_hms)
I get error  "ValueError: not enough values to unpack (expected 2, got 1)"

Please guide me what parameters should I change to avoid this error.  I want to run test.py file instead of mot17_test.sh.
I can run demo file successfully using the provided script.

Thanks in advance.

**Comment by JialianW** [comment]
You need to go to opts.py, which sets the default values of these hyper-parameters.

**Comment by mustansarfiaz** [comment]
@JialianW 

Thank you. Now, I can run the code successfully.
