### ISSUE TITLE
How to set the number of epoch when training my model?

### ISSUE THREAD

**Issue by anthonyweidai** [JialianW/TraDeS#40]
I have used 
`sh experiments/mot17_test.sh
`
to train my own model. And I can set the batch size. Because of the limitation of GPU performance, I changed it from 32 into 4. But I cannot see where to set the number of epoch. BTW, the notification said the program have to go through 140 epochs. I got the noti by running the command.

**Comment by JialianW** [comment]
In opts.py

**Comment by anthonyweidai** [comment]
Thanks bro
