### ISSUE TITLE
2 heads at the same time

### ISSUE THREAD

**Issue by ilbash** [JialianW/TraDeS#41]
Hello! Thank you for this great work! I faced with small problem. I want to use 2 heads at the same time (to predict segmentation mask and 3D bbox). Now I can run it separately - or 3d bbox, or segmentation head. I am ready to take your trained weights and turn on 2 heads at the same time. But I don't understand where in code you turn on segmentation head?
Please help.

best wishes, Ilya

**Comment by JialianW** [comment]
We use the keyword --seg in the run script for turning on the segmentation. You may go to the corresponding code with --seg to see how to run 3D and seg both at the same time.

**Comment by ilbash** [comment]
for example, I want to see the results of segmentation like on your intro video. What command should I type? For example this does not work 
`python demo.py tracking --dataset youtube_vis --pre_hm --demo ../videos/nuscenes_mini.mp4 --pre_thresh 0.5 --track_thresh 0.05 --load_model ../models/coco_seg.pth --gpus 0 --clip_len 2 --trades --box_nms 0.7 --save_video --resize_video --input_h 544 --input_w 960 --seg`

Because of 
<img width="1134" alt="Screenshot 2021-09-17 at 01 00 43" src="https://user-images.githubusercontent.com/25929618/133691444-018eadc9-d7b5-4e63-aa52-414c9e91af02.png">

So what should I type or fix/add in code? Thanks.

**Comment by ilbash** [comment]
@JialianW pls help

**Comment by JialianW** [comment]
Sorry, we didn't provide the segmentation demo code. What I did in the video is that I tested the whole dataset and visualized them on my own.

**Comment by ilbash** [comment]
@JialianW maybe u have that code now? or link to it? just for optimise time. Thanks for understanding

**Comment by JialianW** [comment]
What we have for segmentation now is https://github.com/JialianW/TraDeS/blob/0443c36c2ec716ade2fd2e9748deed1d36f172cd/experiments/youtube_vis.sh

**Comment by ilbash** [comment]
@JialianW yes, I already used it. I want to visualise the results. After your script execution I got json file with results. Maybe u have a code to convert json to visualisation? I got it that right now in your GitHub there is not that code, but maybe u used another code in open source repos. Of course I can analyse the structure in your json and write my own code but it takes time. Thanks for understanding

**Comment by JialianW** [comment]
I believe many instance segmentation github repos have such code.

**Comment by ilbash** [comment]
for future users: if u interested in several heads, u should change the code when model will be being read and results will be being visualised. so write to me and I'll explain.

**Comment by Jx-Tan** [comment]
Hi @Ilyabasharov 
We try to train on mot dataset. But We don't know where Head Network(such as 2D detection, 3D detection and Instace segmentation) plays, can you tell me where this part is in the code.

Thanks a lot.
