### ISSUE TITLE
Questions about result of object detection and instance segmentation

### ISSUE THREAD

**Issue by jjinCode** [JialianW/TraDeS#47]
This research's goal is aimed to 'Good Tracking performance' not individual object detection and instance segmentation performance.
But in my opinion, detection and segmentation module use the tracking feature and tracking module uses detection and segmentation feature, so both of 'tracking' and 'detection and segmentation' performance are improved (in terms of multi-task learning). But you don't mention result of detection or segmentation in this paper. 
I think you could confirm result of detection or segmentation during experiments for writing paper. Do you have any comments to say about this opinion?

Thanks for the good research!!!

**Comment by JialianW** [comment]
Thanks for your interest!

Yes, object detection and instance segmentation shall be improved with the help of tracking cues and temporal context. In our experiments, we follow the common practice of MOT and report FN and FP to reflect the detection performance. For instance segmentation performance, we have reported video-level AP on the Youtube-VIS dataset. We didn't conduct experiments in the image domain task, e.g., image object detection or image instance segmentation, as our method lies in the video domain.
