### ISSUE TITLE
performance of object detection and instance segmentation

### ISSUE THREAD

**Issue by jjinCode** [JialianW/TraDeS#48]
I  this paper, models for detection and segmentation heads are 'CenterNet' and 'CondInst'.
I have a question about comparing results of tasks of branch heads. 
The performances (for detection and segmentation) are increase rather than original standalone each papers or stay same results?
(Only I found is the explanation of FN and FP of detection..)

**Comment by JialianW** [comment]
Both 'CenterNet' and 'CondInst' are for the image domain, while our experiments are all evaluated in the video domain. So there is no overlapping dataset for this comparison in the paper.
