### ISSUE TITLE
About the Head Networks

### ISSUE THREAD

**Issue by Jx-Tan** [JialianW/TraDeS#49]
Thanks for your working.

We try to train on mot dataset. We don't know where Head Network(such as 2D detection, 3D detection and Instace segmentation) plays, can you tell me where this part is in the code.

Thanks a lot.

**Comment by JialianW** [comment]
https://github.com/JialianW/TraDeS/blob/0443c36c2ec716ade2fd2e9748deed1d36f172cd/src/lib/model/networks/base_model.py#L193

**Comment by Jx-Tan** [comment]
I see this code in `for head in self.heads:`, the `self.heads` have some args, such as `hm`、`reg`、`wh`、`ltrb_amodal `, but I don't know what they mean, Can you tell me what they stand or which is stand for segmentation、which is for 2D-detection、and which is for 3D-detection et.al.
Thank for you very much.
