### ISSUE TITLE
error when executing '. make.sh'

### ISSUE THREAD

**Issue by ydm365** [JialianW/TraDeS#54]
I fellow the instructions in INSTALL.md, everything is OK until the last line '. make.sh', which returns `error: command '/usr/bin/nvcc' failed with exit status 1` .
I have noticed there are similar problems while compiling, and I fellow author's suggestion in Issue #2 , but that error occurred again. By the way, my gcc version is 7.5.0, which should be working well.
Can anyone solve this problem? Many appreciations.

**Comment by JialianW** [comment]
Sorry for the late reply. Probably you can find solutions from the GitHub project for DCN, as the compilation issue is from DCN. All my suggested workarounds are also borrowed from the DCN issue section.
