### ISSUE TITLE
What is the graphic memory size during training mot17？

### ISSUE THREAD

**Issue by Bian-666** [JialianW/TraDeS#56]

**Comment by JialianW** [comment]
Sorry, I didn't understand your question.

**Comment by Bian-666** [comment]
> Sorry, I didn't understand your question.

GPU size，
I trained the mot17 with a single RTX3090, it is insufficient to train with a batch size of 32, so i set batch size to 8, but the result of MOTA is only 65.

**Comment by JialianW** [comment]
It could be hard to train on one gpu. Our experiments were done on 4xV100

**Comment by Bian-666** [comment]
thanks for your reply
